services:
  server:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: tugas3-chat-server
    ports:
      - "8088:3000"
    volumes:
      - chat_data:/app/backend/data

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: tugas3-chat-client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  chat_data: